### ISSUE TITLE
More Thanks for Naming Help

### ISSUE THREAD

**Issue by kemitchell** [berneout/round-robin-license#1]
@simerplaha, @excitedleigh, @btburke would each of you be alright with a note of thanks in the `THANKS.md` file of this new repo? I'd like to acknowledge your inputs in a lasting way!

**Comment by BTBurke** [comment]
Sure!  Congrats on the new name.

**Comment by kemitchell** [comment]
@BTBurke, great! See 880faa82ef76848408004a5df0d17c32903b4d69

**Comment by daisylb** [comment]
👍 I love the new name btw!

**Comment by kemitchell** [comment]
@excitedleigh, thanks! See 1f8a489e66a0068642d5486cc22148d823d1b0a1
